# -*- coding: utf-8 -*-
"""
職場情報総合サイト（shokuba.mhlw.go.jp）全件ダウンロード CSV スキーマ定義

構造:
  TABLE_RANGES  : テーブルごとの列インデックス範囲（0始まり、終端は exclusive）
  COLUMN_MAP    : CSV ヘッダー（日本語）→ DB カラム名（英語 snake_case）
  DATE_COLUMNS  : 日付として正規化するカラム名セット（英語名）
  TABLE_INDEXES : テーブルごとのインデックス対象カラム

注意:
  定義ファイル（definition_rawdata_shokuba.csv）では 634 番まで番号が振られているが
  番号なしの行が 2 行存在するため CSV 実列数は 636 列となる場合がある。
  実際の CSV ヘッダーと COLUMN_MAP のキーが一致しない列は col_NNNN 形式で格納する。
"""

# ---------------------------------------------------------------------------
# テーブル分割定義（0-indexed、end は exclusive / None = 末尾まで）
# ---------------------------------------------------------------------------

TABLE_RANGES: list[tuple[str, int, int | None]] = [
    ("shokuba_basic",              0,   39),   # cols 1-39   : 基本情報・就業場所
    ("shokuba_recruitment",       39,  123),   # cols 40-123 : 採用・定着・インターン・社会保険
    ("shokuba_work_hours",       123,  258),   # cols 124-258: 継続勤務年数差異・残業・賃金差異・有給・テレワーク
    ("shokuba_employment_system",258,  390),   # cols 259-390: 多様な正社員制度・転換実績・定年制
    ("shokuba_female_workforce",  390,  418),  # cols 391-418: 女性労働者割合・管理職・役員
    ("shokuba_childcare",         418,  474),  # cols 419-474: 育児休業・両立支援
    ("shokuba_career",            474,  499),  # cols 475-499: キャリア開発・行動計画・自由記述
    ("shokuba_certification",     499, None),  # cols 500-636: 認定・表彰・改善ポータルサイト
]

# ---------------------------------------------------------------------------
# 全列マッピング: CSV ヘッダー（日本語）→ DB カラム名（英語 snake_case）
# ---------------------------------------------------------------------------

COLUMN_MAP: dict[str, str] = {

    # ===== shokuba_basic (cols 1-39) =====
    "法人番号":                                                      "corporate_number",
    "企業名":                                                        "name",
    "ハローワークインターネットサービスの求人掲載-一般求人（フルタイム）":  "hwis_fulltime",
    "ハローワークインターネットサービスの求人掲載-一般求人（パートタイム）": "hwis_parttime",
    "ハローワークインターネットサービスの求人掲載-新卒・既卒求人":         "hwis_graduate",
    "都道府県":                                                      "prefecture",
    "所在地":                                                        "location",
    "就業場所1-就業場所1":                                            "job_loc1_area1",
    "就業場所1-就業場所2":                                            "job_loc1_area2",
    "就業場所1-就業場所3":                                            "job_loc1_area3",
    "就業場所1-求人区分":                                             "job_loc1_job_type",
    "就業場所1-職種":                                                 "job_loc1_occupation",
    "就業場所2-就業場所1":                                            "job_loc2_area1",
    "就業場所2-就業場所2":                                            "job_loc2_area2",
    "就業場所2-就業場所3":                                            "job_loc2_area3",
    "就業場所2-求人区分":                                             "job_loc2_job_type",
    "就業場所2-職種":                                                 "job_loc2_occupation",
    "就業場所3-就業場所1":                                            "job_loc3_area1",
    "就業場所3-就業場所2":                                            "job_loc3_area2",
    "就業場所3-就業場所3":                                            "job_loc3_area3",
    "就業場所3-求人区分":                                             "job_loc3_job_type",
    "就業場所3-職種":                                                 "job_loc3_occupation",
    "就業場所4-就業場所1":                                            "job_loc4_area1",
    "就業場所4-就業場所2":                                            "job_loc4_area2",
    "就業場所4-就業場所3":                                            "job_loc4_area3",
    "就業場所4-職種":                                                 "job_loc4_occupation",
    "代表者（掲載中止）":                                              "representative",
    "企業規模":                                                      "company_size",
    "企業規模詳細":                                                   "company_size_detail",
    "業種":                                                         "industry",
    "事業概要":                                                      "business_summary",
    "企業ホームページ":                                               "homepage_url",
    "採用ページ":                                                    "recruitment_url",
    "電話":                                                         "phone",
    "ＦＡＸ（掲載中止）":                                             "fax",
    "創業年":                                                       "founding_year",
    "証券コード":                                                    "stock_code",
    "市場区分":                                                     "market_segment",
    "公共調達資格情報":                                               "public_procurement_info",

    # ===== shokuba_recruitment (cols 40-123) =====
    "新卒者の採用・定着状況(前年度/2年度前/3年度前)-男性":                         "new_grad_retention_male",
    "新卒者の採用・定着状況(前年度/2年度前/3年度前)-女性":                         "new_grad_retention_female",
    "新卒者の採用・定着状況(前年度/2年度前/3年度前)-男女計":                        "new_grad_retention_total",
    "新卒者の採用・定着状況(前年度/2年度前/3年度前)-離職者数":                       "new_grad_turnover_count",
    "新卒者等以外（35歳未満）の採用・定着状況(前年度/2年度前/3年度前)-男性":           "non_newgrad_retention_male",
    "新卒者等以外（35歳未満）の採用・定着状況(前年度/2年度前/3年度前)-女性":           "non_newgrad_retention_female",
    "新卒者等以外（35歳未満）の採用・定着状況(前年度/2年度前/3年度前)-男女計":          "non_newgrad_retention_total",
    "新卒者等以外（35歳未満）の採用・定着状況(前年度/2年度前/3年度前)-離職者数":        "non_newgrad_turnover_count",
    "再雇用の実績-種別":                                              "rehire_type",
    "再雇用の実績-男性":                                              "rehire_male",
    "再雇用の実績-女性":                                              "rehire_female",
    "再雇用の実績-注記":                                              "rehire_note",
    "中途採用の実績-種別":                                             "midcareer_hire_type",
    "中途採用の実績-男性":                                             "midcareer_hire_male",
    "中途採用の実績-女性":                                             "midcareer_hire_female",
    "中途採用の実績-注記":                                             "midcareer_hire_note",
    "中途採用比率(前年度/2年度前/3年度前)":                              "midcareer_hire_ratio",
    "中途採用比率(公表日)":                                            "midcareer_hire_ratio_date",
    "中途採用・経験者採用の定着率-区分1":                                 "midcareer_retention_category1",
    "中途採用・経験者採用の定着率-経験者等採用人数1":                         "midcareer_retention_hired1",
    "中途採用・経験者採用の定着率-定着者数1":                              "midcareer_retention_count1",
    "中途採用・経験者採用の定着率-定着率1":                               "midcareer_retention_rate1",
    "中途採用・経験者採用の定着率-区分2":                                 "midcareer_retention_category2",
    "中途採用・経験者採用の定着率-経験者等採用人数2":                         "midcareer_retention_hired2",
    "中途採用・経験者採用の定着率-定着者数2":                              "midcareer_retention_count2",
    "中途採用・経験者採用の定着率-定着率2":                               "midcareer_retention_rate2",
    "中途採用・経験者採用の定着率-区分3":                                 "midcareer_retention_category3",
    "中途採用・経験者採用の定着率-経験者等採用人数3":                         "midcareer_retention_hired3",
    "中途採用・経験者採用の定着率-定着者数3":                              "midcareer_retention_count3",
    "中途採用・経験者採用の定着率-定着率3":                               "midcareer_retention_rate3",
    "中途採用・経験者採用の定着率-区分4":                                 "midcareer_retention_category4",
    "中途採用・経験者採用の定着率-経験者等採用人数4":                         "midcareer_retention_hired4",
    "中途採用・経験者採用の定着率-定着者数4":                              "midcareer_retention_count4",
    "中途採用・経験者採用の定着率-定着率4":                               "midcareer_retention_rate4",
    "中途採用・経験者採用の定着率-区分5":                                 "midcareer_retention_category5",
    "中途採用・経験者採用の定着率-経験者等採用人数5":                         "midcareer_retention_hired5",
    "中途採用・経験者採用の定着率-定着者数5":                              "midcareer_retention_count5",
    "中途採用・経験者採用の定着率-定着率5":                               "midcareer_retention_rate5",
    "中途採用・経験者採用の定着率-区分6":                                 "midcareer_retention_category6",
    "中途採用・経験者採用の定着率-経験者等採用人数6":                         "midcareer_retention_hired6",
    "中途採用・経験者採用の定着率-定着者数6":                              "midcareer_retention_count6",
    "中途採用・経験者採用の定着率-定着率6":                               "midcareer_retention_rate6",
    "中途採用・経験者採用の定着率-備考":                                  "midcareer_retention_note",
    "採用した労働者に占める女性労働者の割合-雇用管理区分(一覧)":               "hired_female_ratio_category_list",
    "採用した労働者に占める女性労働者の割合-割合(一覧)":                     "hired_female_ratio_list",
    "採用した労働者に占める女性労働者の割合-注記(一覧)":                     "hired_female_ratio_note_list",
    "採用した労働者に占める女性労働者の割合-雇用管理区分1(詳細)":              "hired_female_ratio_category1",
    "採用した労働者に占める女性労働者の割合-雇用管理区分1女性(詳細)":           "hired_female_ratio1",
    "採用した労働者に占める女性労働者の割合-雇用管理区分2(詳細)":              "hired_female_ratio_category2",
    "採用した労働者に占める女性労働者の割合-雇用管理区分2女性(詳細)":           "hired_female_ratio2",
    "採用した労働者に占める女性労働者の割合-雇用管理区分3(詳細)":              "hired_female_ratio_category3",
    "採用した労働者に占める女性労働者の割合-雇用管理区分3女性(詳細)":           "hired_female_ratio3",
    "採用した労働者に占める女性労働者の割合-雇用管理区分4(詳細)":              "hired_female_ratio_category4",
    "採用した労働者に占める女性労働者の割合-雇用管理区分4女性(詳細)":           "hired_female_ratio4",
    "採用した労働者に占める女性労働者の割合-雇用管理区分5(詳細)":              "hired_female_ratio_category5",
    "採用した労働者に占める女性労働者の割合-雇用管理区分5女性(詳細)":           "hired_female_ratio5",
    "採用した労働者に占める女性労働者の割合-注記(詳細)":                     "hired_female_ratio_note",
    "採用における男女別の競争倍率-種別(一覧)":                             "hire_competition_type_list",
    "採用における男女別の競争倍率-範囲(一覧)":                             "hire_competition_range_list",
    "採用における男女別の競争倍率-男性(一覧)":                             "hire_competition_male_list",
    "採用における男女別の競争倍率-女性(一覧)":                             "hire_competition_female_list",
    "採用における男女別の競争倍率-注記(一覧)":                             "hire_competition_note_list",
    "採用における男女別の競争倍率-雇用管理区分1（詳細）":                     "hire_competition_category1",
    "採用における男女別の競争倍率-男性1（詳細）":                           "hire_competition_male1",
    "採用における男女別の競争倍率-女性1（詳細）":                           "hire_competition_female1",
    "採用における男女別の競争倍率-雇用管理区分2（詳細）":                     "hire_competition_category2",
    "採用における男女別の競争倍率-男性2（詳細）":                           "hire_competition_male2",
    "採用における男女別の競争倍率-女性2（詳細）":                           "hire_competition_female2",
    "採用における男女別の競争倍率-雇用管理区分3（詳細）":                     "hire_competition_category3",
    "採用における男女別の競争倍率-男性3（詳細）":                           "hire_competition_male3",
    "採用における男女別の競争倍率-女性3（詳細）":                           "hire_competition_female3",
    "採用における男女別の競争倍率-雇用管理区分4（詳細）":                     "hire_competition_category4",
    "採用における男女別の競争倍率-男性4（詳細）":                           "hire_competition_male4",
    "採用における男女別の競争倍率-女性4（詳細）":                           "hire_competition_female4",
    "採用における男女別の競争倍率-雇用管理区分5（詳細）":                     "hire_competition_category5",
    "採用における男女別の競争倍率-男性5（詳細）":                           "hire_competition_male5",
    "採用における男女別の競争倍率-女性5（詳細）":                           "hire_competition_female5",
    "採用における男女別の競争倍率-注記（詳細）":                            "hire_competition_note",
    "インターンシップの受入-可否":                                        "internship_available",
    "インターンシップの受入-内容":                                        "internship_detail",
    "職場見学・職場体験の受入-可否":                                       "workplace_visit_available",
    "職場見学・職場体験の受入-内容":                                       "workplace_visit_detail",
    "社会保険の有無":                                                  "social_insurance",
    "短時間労働者の社会保険適用の有無":                                    "parttime_social_insurance",

    # ===== shokuba_work_hours (cols 124-258) =====
    "男女の平均継続勤務年数の差異-種別（一覧）":                             "tenure_gap_type_list",
    "男女の平均継続勤務年数の差異-範囲（一覧）":                             "tenure_gap_range_list",
    "男女の平均継続勤務年数の差異-男性（一覧）":                             "tenure_gap_male_list",
    "男女の平均継続勤務年数の差異-女性（一覧）":                             "tenure_gap_female_list",
    "男女の平均継続勤務年数の差異-差異（一覧）":                             "tenure_gap_diff_list",
    "男女の平均継続勤務年数の差異-差異根拠（一覧）":                          "tenure_gap_reason_list",
    "男女の平均継続勤務年数の差異-注記(一覧)":                              "tenure_gap_note_list",
    "男女の平均継続勤務年数の差異-雇用管理区分1（詳細）":                      "tenure_gap_category1",
    "男女の平均継続勤務年数の差異-男性1（詳細）":                            "tenure_gap_male1",
    "男女の平均継続勤務年数の差異-女性1（詳細）":                            "tenure_gap_female1",
    "男女の平均継続勤務年数の差異-差異1（詳細）":                            "tenure_gap_diff1",
    "男女の平均継続勤務年数の差異-差異根拠1（詳細）":                         "tenure_gap_reason1",
    "男女の平均継続勤務年数の差異-雇用管理区分2（詳細）":                      "tenure_gap_category2",
    "男女の平均継続勤務年数の差異-男性2（詳細）":                            "tenure_gap_male2",
    "男女の平均継続勤務年数の差異-女性2（詳細）":                            "tenure_gap_female2",
    "男女の平均継続勤務年数の差異-差異2（詳細）":                            "tenure_gap_diff2",
    "男女の平均継続勤務年数の差異-差異根拠2（詳細）":                         "tenure_gap_reason2",
    "男女の平均継続勤務年数の差異-雇用管理区分3（詳細）":                      "tenure_gap_category3",
    "男女の平均継続勤務年数の差異-男性3（詳細）":                            "tenure_gap_male3",
    "男女の平均継続勤務年数の差異-女性3（詳細）":                            "tenure_gap_female3",
    "男女の平均継続勤務年数の差異-差異3（詳細）":                            "tenure_gap_diff3",
    "男女の平均継続勤務年数の差異-差異根拠3（詳細）":                         "tenure_gap_reason3",
    "男女の平均継続勤務年数の差異-雇用管理区分4（詳細）":                      "tenure_gap_category4",
    "男女の平均継続勤務年数の差異-男性4（詳細）":                            "tenure_gap_male4",
    "男女の平均継続勤務年数の差異-女性4（詳細）":                            "tenure_gap_female4",
    "男女の平均継続勤務年数の差異-差異4（詳細）":                            "tenure_gap_diff4",
    "男女の平均継続勤務年数の差異-差異根拠4（詳細）":                         "tenure_gap_reason4",
    "男女の平均継続勤務年数の差異-雇用管理区分5（詳細）":                      "tenure_gap_category5",
    "男女の平均継続勤務年数の差異-男性5（詳細）":                            "tenure_gap_male5",
    "男女の平均継続勤務年数の差異-女性5（詳細）":                            "tenure_gap_female5",
    "男女の平均継続勤務年数の差異-差異5（詳細）":                            "tenure_gap_diff5",
    "男女の平均継続勤務年数の差異-差異根拠5（詳細）":                         "tenure_gap_reason5",
    "男女の平均継続勤務年数の差異-注記（詳細）":                             "tenure_gap_note",
    "正社員の平均継続勤務年数":                                           "avg_tenure_fulltime",
    "男女別採用10年前後の継続雇用割合-種別（一覧）":                          "retention_10yr_type_list",
    "男女別採用10年前後の継続雇用割合-範囲（一覧）":                          "retention_10yr_range_list",
    "男女別採用10年前後の継続雇用割合-男性（一覧）":                          "retention_10yr_male_list",
    "男女別採用10年前後の継続雇用割合-女性（一覧）":                          "retention_10yr_female_list",
    "男女別採用10年前後の継続雇用割合-注記(一覧)":                           "retention_10yr_note_list",
    "男女別採用10年前後の継続雇用割合-雇用管理区分1（詳細）":                   "retention_10yr_category1",
    "男女別採用10年前後の継続雇用割合-男性1（詳細）":                         "retention_10yr_male1",
    "男女別採用10年前後の継続雇用割合-女性1（詳細）":                         "retention_10yr_female1",
    "男女別採用10年前後の継続雇用割合-雇用管理区分2（詳細）":                   "retention_10yr_category2",
    "男女別採用10年前後の継続雇用割合-男性2（詳細）":                         "retention_10yr_male2",
    "男女別採用10年前後の継続雇用割合-女性2（詳細）":                         "retention_10yr_female2",
    "男女別採用10年前後の継続雇用割合-雇用管理区分3（詳細）":                   "retention_10yr_category3",
    "男女別採用10年前後の継続雇用割合-男性3（詳細）":                         "retention_10yr_male3",
    "男女別採用10年前後の継続雇用割合-女性3（詳細）":                         "retention_10yr_female3",
    "男女別採用10年前後の継続雇用割合-雇用管理区分4（詳細）":                   "retention_10yr_category4",
    "男女別採用10年前後の継続雇用割合-男性4（詳細）":                         "retention_10yr_male4",
    "男女別採用10年前後の継続雇用割合-女性4（詳細）":                         "retention_10yr_female4",
    "男女別採用10年前後の継続雇用割合-雇用管理区分5（詳細）":                   "retention_10yr_category5",
    "男女別採用10年前後の継続雇用割合-男性5（詳細）":                         "retention_10yr_male5",
    "男女別採用10年前後の継続雇用割合-女性5（詳細）":                         "retention_10yr_female5",
    "男女別採用10年前後の継続雇用割合-注記（詳細）":                          "retention_10yr_note",
    "従業員の平均年齢":                                                  "avg_employee_age",
    "36協定及び特例時の上限-36協定の有無":                                  "overtime_agreement_exists",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-事業所名":
        "overtime_max_business_name",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-業務名":
        "overtime_max_task_name",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-1日の延長可能時間":
        "overtime_max_daily_hours",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-指定期間の延長可能時間（期間）":
        "overtime_max_period_range",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-指定期間の延長可能時間":
        "overtime_max_period_hours",
    "36協定及び特例時の上限-企業内における、1か月の延長可能時間が最も長い業務-1年の延長可能時間":
        "overtime_max_annual_hours",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-事業所名":
        "overtime_major_business_name",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-業務名":
        "overtime_major_task_name",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-1日の延長可能時間":
        "overtime_major_daily_hours",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-指定期間の延長可能時間（期間）":
        "overtime_major_period_range",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-指定期間の延長可能時間":
        "overtime_major_period_hours",
    "36協定及び特例時の上限-企業内において最も多くの労働者が従事している業務-1年の延長可能時間":
        "overtime_major_annual_hours",
    "36協定及び特例時の上限-36協定に関する備考":                             "overtime_agreement_note",
    "月平均所定外労働時間":                                               "avg_overtime_hours_monthly",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-雇用管理区分１":           "overtime_by_category1",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-平均残業時間１":           "overtime_hours_category1",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-雇用管理区分２":           "overtime_by_category2",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-平均残業時間２":           "overtime_hours_category2",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-雇用管理区分３":           "overtime_by_category3",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-平均残業時間３":           "overtime_hours_category3",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-雇用管理区分４":           "overtime_by_category4",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-平均残業時間４":           "overtime_hours_category4",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-雇用管理区分５":           "overtime_by_category5",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-平均残業時間５":           "overtime_hours_category5",
    "雇用管理区分ごとの一月当たりの労働者の平均残業時間-注記":                   "overtime_by_category_note",
    "対象労働者全体の月平均の法定時間外労働時間と法定休日労働時間の合計-範囲（詳細）":  "legal_overtime_range",
    "対象労働者全体の月平均の法定時間外労働時間と法定休日労働時間の合計-平均残業時間（詳細）": "legal_overtime_hours",
    "対象労働者全体の月平均の法定時間外労働時間と法定休日労働時間の合計-取組内容（詳細）": "legal_overtime_initiatives",
    "対象労働者全体の月平均の法定時間外労働時間と法定休日労働時間の合計-注記（詳細）":  "legal_overtime_note",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-1月":  "monthly_overtime_jan",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-2月":  "monthly_overtime_feb",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-3月":  "monthly_overtime_mar",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-4月":  "monthly_overtime_apr",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-5月":  "monthly_overtime_may",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-6月":  "monthly_overtime_jun",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-7月":  "monthly_overtime_jul",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-8月":  "monthly_overtime_aug",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-9月":  "monthly_overtime_sep",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-10月": "monthly_overtime_oct",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-11月": "monthly_overtime_nov",
    "フルタイムの労働者等1人あたりの各月ごとの時間外労働及び休日労働の合計時間数-12月": "monthly_overtime_dec",
    "平均の法定時間外労働60時間以上の労働者の数":                             "workers_overtime_60h_plus",
    "男女の賃金の差異-全労働者":                                           "pay_gap_all_workers",
    "男女の賃金の差異-うち正規雇用労働者":                                   "pay_gap_regular_workers",
    "男女の賃金の差異-うち非正規雇用労働者":                                  "pay_gap_nonregular_workers",
    "男女の賃金の差異-区分1":                                             "pay_gap_category1",
    "男女の賃金の差異-割合1":                                             "pay_gap_ratio1",
    "男女の賃金の差異-区分2":                                             "pay_gap_category2",
    "男女の賃金の差異-割合2":                                             "pay_gap_ratio2",
    "男女の賃金の差異-区分3":                                             "pay_gap_category3",
    "男女の賃金の差異-割合3":                                             "pay_gap_ratio3",
    "男女の賃金の差異-区分4":                                             "pay_gap_category4",
    "男女の賃金の差異-割合4":                                             "pay_gap_ratio4",
    "男女の賃金の差異-区分5":                                             "pay_gap_category5",
    "男女の賃金の差異-割合5":                                             "pay_gap_ratio5",
    "男女の賃金の差異-対象期間":                                           "pay_gap_period",
    "男女の賃金の差異-注釈・説明":                                          "pay_gap_note",
    "正社員の有給休暇取得日数":                                            "paid_leave_days_fulltime",
    "年次有給休暇取得率（雇用管理区分）-範囲（一覧）":                          "paid_leave_rate_range_list",
    "年次有給休暇取得率（雇用管理区分）-取得率（一覧）":                         "paid_leave_rate_list",
    "年次有給休暇取得率（雇用管理区分）-注記(一覧)":                           "paid_leave_rate_note_list",
    "年次有給休暇取得率（雇用管理区分）-雇用管理区分1（詳細）":                   "paid_leave_rate_category1",
    "年次有給休暇取得率（雇用管理区分）-取得率1（詳細）":                        "paid_leave_rate1",
    "年次有給休暇取得率（雇用管理区分）-雇用管理区分2（詳細）":                   "paid_leave_rate_category2",
    "年次有給休暇取得率（雇用管理区分）-取得率2（詳細）":                        "paid_leave_rate2",
    "年次有給休暇取得率（雇用管理区分）-雇用管理区分3（詳細）":                   "paid_leave_rate_category3",
    "年次有給休暇取得率（雇用管理区分）-取得率3（詳細）":                        "paid_leave_rate3",
    "年次有給休暇取得率（雇用管理区分）-雇用管理区分4（詳細）":                   "paid_leave_rate_category4",
    "年次有給休暇取得率（雇用管理区分）-取得率4（詳細）":                        "paid_leave_rate4",
    "年次有給休暇取得率（雇用管理区分）-雇用管理区分5（詳細）":                   "paid_leave_rate_category5",
    "年次有給休暇取得率（雇用管理区分）-取得率5（詳細）":                        "paid_leave_rate5",
    "年次有給休暇取得率（雇用管理区分）-注記（詳細）":                           "paid_leave_rate_note",
    "年次有給休暇取得率（全体）-取得率":                                      "paid_leave_rate_overall",
    "年次有給休暇取得率（全体）-注記":                                        "paid_leave_rate_overall_note",
    "テレワーク制度-可否":                                               "telework_available",
    "テレワーク制度-制度内容":                                             "telework_detail",
    "副業・兼業-可否":                                                  "side_job_available",
    "副業・兼業-副業・兼業にあたっての留意事項等":                              "side_job_note",

    # ===== shokuba_employment_system (cols 259-390) =====
    "多様な正社員制度-制度-職務限定正社員":                                   "diverse_employment_job_limited",
    "多様な正社員制度-制度-勤務地限定正社員":                                  "diverse_employment_location_limited",
    "多様な正社員制度-制度-短時間正社員":                                     "diverse_employment_short_time",
    "多様な正社員制度-その他の内容":                                         "diverse_employment_other",
    "多様な正社員制度-制度内容等説明欄":                                      "diverse_employment_detail",
    "多様な正社員制度-区分1":   "diverse_emp_category1",
    "多様な正社員制度-正規雇用労働者数1": "diverse_emp_regular_count1",
    "多様な正社員制度-制度利用者数1":   "diverse_emp_users1",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合1": "diverse_emp_ratio1",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数1": "diverse_emp_converted1",
    "多様な正社員制度-区分2":   "diverse_emp_category2",
    "多様な正社員制度-正規雇用労働者数2": "diverse_emp_regular_count2",
    "多様な正社員制度-制度利用者数2":   "diverse_emp_users2",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合2": "diverse_emp_ratio2",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数2": "diverse_emp_converted2",
    "多様な正社員制度-区分3":   "diverse_emp_category3",
    "多様な正社員制度-正規雇用労働者数3": "diverse_emp_regular_count3",
    "多様な正社員制度-制度利用者数3":   "diverse_emp_users3",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合3": "diverse_emp_ratio3",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数3": "diverse_emp_converted3",
    "多様な正社員制度-区分4":   "diverse_emp_category4",
    "多様な正社員制度-正規雇用労働者数4": "diverse_emp_regular_count4",
    "多様な正社員制度-制度利用者数4":   "diverse_emp_users4",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合4": "diverse_emp_ratio4",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数4": "diverse_emp_converted4",
    "多様な正社員制度-区分5":   "diverse_emp_category5",
    "多様な正社員制度-正規雇用労働者数5": "diverse_emp_regular_count5",
    "多様な正社員制度-制度利用者数5":   "diverse_emp_users5",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合5": "diverse_emp_ratio5",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数5": "diverse_emp_converted5",
    "多様な正社員制度-区分6":   "diverse_emp_category6",
    "多様な正社員制度-正規雇用労働者数6": "diverse_emp_regular_count6",
    "多様な正社員制度-制度利用者数6":   "diverse_emp_users6",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合6": "diverse_emp_ratio6",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数6": "diverse_emp_converted6",
    "多様な正社員制度-区分7":   "diverse_emp_category7",
    "多様な正社員制度-正規雇用労働者数7": "diverse_emp_regular_count7",
    "多様な正社員制度-制度利用者数7":   "diverse_emp_users7",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合7": "diverse_emp_ratio7",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数7": "diverse_emp_converted7",
    "多様な正社員制度-区分8":   "diverse_emp_category8",
    "多様な正社員制度-正規雇用労働者数8": "diverse_emp_regular_count8",
    "多様な正社員制度-制度利用者数8":   "diverse_emp_users8",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合8": "diverse_emp_ratio8",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数8": "diverse_emp_converted8",
    "多様な正社員制度-区分9":   "diverse_emp_category9",
    "多様な正社員制度-正規雇用労働者数9": "diverse_emp_regular_count9",
    "多様な正社員制度-制度利用者数9":   "diverse_emp_users9",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合9": "diverse_emp_ratio9",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数9": "diverse_emp_converted9",
    "多様な正社員制度-区分10":  "diverse_emp_category10",
    "多様な正社員制度-正規雇用労働者数10": "diverse_emp_regular_count10",
    "多様な正社員制度-制度利用者数10":  "diverse_emp_users10",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合10": "diverse_emp_ratio10",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数10": "diverse_emp_converted10",
    "多様な正社員制度-区分11":  "diverse_emp_category11",
    "多様な正社員制度-正規雇用労働者数11": "diverse_emp_regular_count11",
    "多様な正社員制度-制度利用者数11":  "diverse_emp_users11",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合11": "diverse_emp_ratio11",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数11": "diverse_emp_converted11",
    "多様な正社員制度-区分12":  "diverse_emp_category12",
    "多様な正社員制度-正規雇用労働者数12": "diverse_emp_regular_count12",
    "多様な正社員制度-制度利用者数12":  "diverse_emp_users12",
    "多様な正社員制度-正規雇用労働者に占める制度利用者の割合12": "diverse_emp_ratio12",
    "多様な正社員制度-非正規雇用労働者から転換して制度を利用している者の数12": "diverse_emp_converted12",
    "多様な正社員制度-備考":                                             "diverse_emp_note",
    "正社員転換制度-有無":                                               "regular_conversion_exists",
    "正社員転換制度-制度内容":                                            "regular_conversion_detail",
    "職種形態の転換実績-種別(一覧)":                                       "job_type_change_type_list",
    "職種形態の転換実績-転換内容(一覧)":                                    "job_type_change_content_list",
    "職種形態の転換実績-男性(一覧)":                                       "job_type_change_male_list",
    "職種形態の転換実績-女性(一覧)":                                       "job_type_change_female_list",
    "職種形態の転換実績-注記(一覧)":                                       "job_type_change_note_list",
    "職種形態の転換実績-雇用管理区分1（詳細）":                               "job_type_change_category1",
    "職種形態の転換実績-男性1（詳細）":                                     "job_type_change_male1",
    "職種形態の転換実績-女性1（詳細）":                                     "job_type_change_female1",
    "職種形態の転換実績-雇用管理区分2（詳細）":                               "job_type_change_category2",
    "職種形態の転換実績-男性2（詳細）":                                     "job_type_change_male2",
    "職種形態の転換実績-女性2（詳細）":                                     "job_type_change_female2",
    "職種形態の転換実績-雇用管理区分3（詳細）":                               "job_type_change_category3",
    "職種形態の転換実績-男性3（詳細）":                                     "job_type_change_male3",
    "職種形態の転換実績-女性3（詳細）":                                     "job_type_change_female3",
    "職種形態の転換実績-雇用管理区分4（詳細）":                               "job_type_change_category4",
    "職種形態の転換実績-男性4（詳細）":                                     "job_type_change_male4",
    "職種形態の転換実績-女性4（詳細）":                                     "job_type_change_female4",
    "職種形態の転換実績-雇用管理区分5（詳細）":                               "job_type_change_category5",
    "職種形態の転換実績-男性5（詳細）":                                     "job_type_change_male5",
    "職種形態の転換実績-女性5（詳細）":                                     "job_type_change_female5",
    "職種形態の転換実績-注記（詳細）":                                       "job_type_change_note",
    "雇用形態の転換実績-種別(一覧)":                                       "employment_type_change_type_list",
    "雇用形態の転換実績-転換内容(一覧)":                                    "employment_type_change_content_list",
    "雇用形態の転換実績-男性(一覧)":                                       "employment_type_change_male_list",
    "雇用形態の転換実績-女性(一覧)":                                       "employment_type_change_female_list",
    "雇用形態の転換実績-注記(一覧)":                                       "employment_type_change_note_list",
    "雇用形態の転換実績-雇用管理区分1（詳細）":                               "employment_type_change_category1",
    "雇用形態の転換実績-男性1（詳細）":                                     "employment_type_change_male1",
    "雇用形態の転換実績-女性1（詳細）":                                     "employment_type_change_female1",
    "雇用形態の転換実績-雇用管理区分2（詳細）":                               "employment_type_change_category2",
    "雇用形態の転換実績-男性2（詳細）":                                     "employment_type_change_male2",
    "雇用形態の転換実績-女性2（詳細）":                                     "employment_type_change_female2",
    "雇用形態の転換実績-雇用管理区分3（詳細）":                               "employment_type_change_category3",
    "雇用形態の転換実績-男性3（詳細）":                                     "employment_type_change_male3",
    "雇用形態の転換実績-女性3（詳細）":                                     "employment_type_change_female3",
    "雇用形態の転換実績-雇用管理区分4（詳細）":                               "employment_type_change_category4",
    "雇用形態の転換実績-男性4（詳細）":                                     "employment_type_change_male4",
    "雇用形態の転換実績-女性4（詳細）":                                     "employment_type_change_female4",
    "雇用形態の転換実績-雇用管理区分5（詳細）":                               "employment_type_change_category5",
    "雇用形態の転換実績-男性5（詳細）":                                     "employment_type_change_male5",
    "雇用形態の転換実績-女性5（詳細）":                                     "employment_type_change_female5",
    "雇用形態の転換実績-注記（詳細）":                                       "employment_type_change_note",
    "定年制-定年年齢1":  "retirement_age1",
    "定年制-職種・事業所名等1": "retirement_job_name1",
    "定年制-定年年齢2":  "retirement_age2",
    "定年制-職種・事業所名等2": "retirement_job_name2",
    "定年制-定年年齢3":  "retirement_age3",
    "定年制-職種・事業所名等3": "retirement_job_name3",
    "定年制-定年年齢4":  "retirement_age4",
    "定年制-職種・事業所名等4": "retirement_job_name4",
    "定年制-定年年齢5":  "retirement_age5",
    "定年制-職種・事業所名等5": "retirement_job_name5",
    "定年制-留意事項":   "retirement_note",
    "定年制-継続雇用制度-上限年齢1": "continued_employment_max_age1",
    "定年制-継続雇用制度-職種・事業所名等1": "continued_employment_job1",
    "定年制-継続雇用制度-上限年齢2": "continued_employment_max_age2",
    "定年制-継続雇用制度-職種・事業所名等2": "continued_employment_job2",
    "定年制-継続雇用制度-上限年齢3": "continued_employment_max_age3",
    "定年制-継続雇用制度-職種・事業所名等3": "continued_employment_job3",
    "定年制-継続雇用制度-上限年齢4": "continued_employment_max_age4",
    "定年制-継続雇用制度-職種・事業所名等4": "continued_employment_job4",
    "定年制-継続雇用制度-上限年齢5": "continued_employment_max_age5",
    "定年制-継続雇用制度-職種・事業所名等5": "continued_employment_job5",
    "定年制-留意事項・その他": "retirement_other_note",

    # ===== shokuba_female_workforce (cols 391-418) =====
    "労働者に占める女性労働者の割合-範囲（一覧）":                             "female_worker_ratio_range_list",
    "労働者に占める女性労働者の割合-女性（一覧）":                             "female_worker_ratio_list",
    "労働者に占める女性労働者の割合-注記（一覧）":                             "female_worker_ratio_note_list",
    "労働者に占める女性労働者の割合-雇用管理区分1（詳細）":                      "female_worker_ratio_category1",
    "労働者に占める女性労働者の割合-女性1（詳細）":                            "female_worker_ratio1",
    "労働者に占める女性労働者の割合-雇用管理区分2（詳細）":                      "female_worker_ratio_category2",
    "労働者に占める女性労働者の割合-女性2（詳細）":                            "female_worker_ratio2",
    "労働者に占める女性労働者の割合-雇用管理区分3（詳細）":                      "female_worker_ratio_category3",
    "労働者に占める女性労働者の割合-女性3（詳細）":                            "female_worker_ratio3",
    "労働者に占める女性労働者の割合-雇用管理区分4（詳細）":                      "female_worker_ratio_category4",
    "労働者に占める女性労働者の割合-女性4（詳細）":                            "female_worker_ratio4",
    "労働者に占める女性労働者の割合-雇用管理区分5（詳細）":                      "female_worker_ratio_category5",
    "労働者に占める女性労働者の割合-女性5（詳細）":                            "female_worker_ratio5",
    "労働者に占める女性労働者の割合-注記（詳細）":                             "female_worker_ratio_note",
    "係長級にある者に占める女性労働者の割合-割合":                             "female_section_chief_ratio",
    "係長級にある者に占める女性労働者の割合-人数":                             "female_section_chief_count",
    "係長級にある者に占める女性労働者の割合-男女計":                            "section_chief_total",
    "係長級にある者に占める女性労働者の割合-注記":                             "female_section_chief_note",
    "管理職に占める女性の割合":                                           "female_manager_ratio",
    "女性管理職人数":                                                  "female_manager_count",
    "管理職全体人数（男女計）":                                           "total_manager_count",
    "直近3事業年度における男女別の課長級より一つ下の職階から課長級に昇進した割合-直近の3事業開始年度":
        "promotion_to_manager_start_year",
    "直近3事業年度における男女別の課長級より一つ下の職階から課長級に昇進した割合-直近の3事業終了年度":
        "promotion_to_manager_end_year",
    "直近3事業年度における男女別の課長級より一つ下の職階から課長級に昇進した割合-男性割合":
        "promotion_to_manager_male_ratio",
    "直近3事業年度における男女別の課長級より一つ下の職階から課長級に昇進した割合-女性割合":
        "promotion_to_manager_female_ratio",
    "役員に占める女性の割合":                                            "female_executive_ratio",
    "女性役員人数":                                                   "female_executive_count",
    "役員全体人数（男女計）":                                            "total_executive_count",

    # ===== shokuba_childcare (cols 419-474) =====
    "育児休業対象者数（男性）":                                           "childcare_leave_eligible_male",
    "育児休業対象者数（女性）":                                           "childcare_leave_eligible_female",
    "育児休業取得者数（男性）":                                           "childcare_leave_takers_male",
    "育児休業取得者数（女性）":                                           "childcare_leave_takers_female",
    "育児休業取得率（男性）-種別（一覧）":                                   "childcare_leave_rate_male_type_list",
    "育児休業取得率（男性）-範囲（一覧）":                                   "childcare_leave_rate_male_range_list",
    "育児休業取得率（男性）-男性取得率（一覧）":                               "childcare_leave_rate_male_list",
    "育児休業取得率（男性）-注記（一覧）":                                   "childcare_leave_rate_male_note_list",
    "育児休業取得率（男性）-雇用管理区分1（詳細）":                            "childcare_leave_rate_male_category1",
    "育児休業取得率（男性）-男性取得率1（詳細）":                             "childcare_leave_rate_male1",
    "育児休業取得率（男性）-雇用管理区分2（詳細）":                            "childcare_leave_rate_male_category2",
    "育児休業取得率（男性）-男性取得率2（詳細）":                             "childcare_leave_rate_male2",
    "育児休業取得率（男性）-雇用管理区分3（詳細）":                            "childcare_leave_rate_male_category3",
    "育児休業取得率（男性）-男性取得率3（詳細）":                             "childcare_leave_rate_male3",
    "育児休業取得率（男性）-雇用管理区分4（詳細）":                            "childcare_leave_rate_male_category4",
    "育児休業取得率（男性）-男性取得率4（詳細）":                             "childcare_leave_rate_male4",
    "育児休業取得率（男性）-雇用管理区分5（詳細）":                            "childcare_leave_rate_male_category5",
    "育児休業取得率（男性）-男性取得率5（詳細）":                             "childcare_leave_rate_male5",
    "育児休業取得率（男性）-注記（詳細）":                                   "childcare_leave_rate_male_note",
    "育児休業取得率（女性）-種別（一覧）":                                   "childcare_leave_rate_female_type_list",
    "育児休業取得率（女性）-範囲（一覧）":                                   "childcare_leave_rate_female_range_list",
    "育児休業取得率（女性）-女性取得率（一覧）":                               "childcare_leave_rate_female_list",
    "育児休業取得率（女性）-注記（一覧）":                                   "childcare_leave_rate_female_note_list",
    "育児休業取得率（女性）-雇用管理区分1（詳細）":                            "childcare_leave_rate_female_category1",
    "育児休業取得率（女性）-女性取得率1（詳細）":                             "childcare_leave_rate_female1",
    "育児休業取得率（女性）-雇用管理区分2（詳細）":                            "childcare_leave_rate_female_category2",
    "育児休業取得率（女性）-女性取得率2（詳細）":                             "childcare_leave_rate_female2",
    "育児休業取得率（女性）-雇用管理区分3（詳細）":                            "childcare_leave_rate_female_category3",
    "育児休業取得率（女性）-女性取得率3（詳細）":                             "childcare_leave_rate_female3",
    "育児休業取得率（女性）-雇用管理区分4（詳細）":                            "childcare_leave_rate_female_category4",
    "育児休業取得率（女性）-女性取得率4（詳細）":                             "childcare_leave_rate_female4",
    "育児休業取得率（女性）-雇用管理区分5（詳細）":                            "childcare_leave_rate_female_category5",
    "育児休業取得率（女性）-女性取得率5（詳細）":                             "childcare_leave_rate_female5",
    "育児休業取得率（女性）-注記（詳細）":                                   "childcare_leave_rate_female_note",
    "育児休業取得実績-公表前事業年度において、配偶者が出産した男性労働者数に対する、育児休業等をした男性労働者数の割合":
        "childcare_leave_male_spouse_birth_ratio",
    "育児休業取得実績-公表前事業年度において、出産した女性労働者数に対する、育児休業等をした女性労働者数の割合":
        "childcare_leave_female_birth_ratio",
    "育児休業取得実績-公表前事業年度において、配偶者が出産した男性労働者のうち公表前事業年度において育児休業等をした男性労働者数":
        "childcare_leave_male_takers_count",
    "育児休業取得実績-公表前事業年度において、配偶者が出産した男性労働者数に対する、育児休業等をした男性労働者数及び育児目的休暇制度を利用した男性労働者数の合計数の割合":
        "childcare_leave_male_combined_ratio",
    "育児目的休暇制度の具体的内容":                                        "childcare_purpose_leave_detail",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-育児休業に関する制度に準ずる措置":
        "childcare_short_time_leave_measure",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-所定外労働の制限":
        "childcare_short_time_overtime_limit",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-短時間勤務制度":
        "childcare_short_time_system",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-フレックスタイム制度":
        "childcare_flex_time",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-始業・終業時刻の繰上げ又は繰下げの制度":
        "childcare_flex_hours",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-事業所内保育施設の設置運営":
        "childcare_onsite_facility",
    "3歳から小学校就学の始期に達するまでの子を育てる労働者のために実施している短時間勤務制度等の措置の内容-育児に要する経費の援助措置等":
        "childcare_expense_support",
    "公表前事業年度において看護休暇を取得した男性労働者数":                      "nursing_leave_male_count",
    "公表前事業年度において短時間勤務制度等を子の養育のために使用した男性労働者数":   "short_time_for_childcare_male",
    "公表前事業年度において育児目的休暇制度を15歳に達する日以後の最初の3月31日までの間にある子又は小学校就学前までの孫のために利用した男性労働者数":
        "childcare_purpose_leave_male_users",
    "所定外労働削減のための措置の内容":                                      "overtime_reduction_measures",
    "年次有給休暇取得促進のための措置内容":                                   "paid_leave_promotion_measures",
    "短時間正社員制度、在宅勤務、テレワークその他の働き方の見直しに資する多様な労働条件の整備のための措置の内容":
        "diverse_work_conditions_measures",
    "公表前々事業年度において出産した女性労働者数に対する、公表前事業年度に在職している又は在職していた女性労働者数の割合":
        "female_retention_after_birth_ratio",
    "育休・育児を行う女性労働者の能力向上・キャリア形成支援のための取組に係る計画の内容":
        "female_career_support_plan",
    "育休・育児を行う女性労働者の能力向上・キャリア形成支援のための取組に係る計画の内容の実施状況":
        "female_career_support_plan_status",
    "公表前々事業年度において出産した女性労働者数及び公表前々事業年度において出産予定であった女性労働者のうち退職した女性労働者数の合計数に対する公表前事業年度に在職していた女性労働者数の割合":
        "female_retention_adjusted_ratio",

    # ===== shokuba_career (cols 475-499) =====
    "研修制度-有無":                                                   "training_system_exists",
    "研修制度-内容":                                                   "training_system_detail",
    "メンター制度-有無":                                                 "mentor_system_exists",
    "自己啓発支援制度-有無":                                             "self_development_exists",
    "自己啓発支援制度-内容":                                             "self_development_detail",
    "キャリアコンサルティング制度-有無":                                    "career_consulting_exists",
    "キャリアコンサルティング制度-内容":                                    "career_consulting_detail",
    "社内検定制度-有無":                                                "internal_certification_exists",
    "社内検定制度-内容":                                                "internal_certification_detail",
    "取得可能資格":                                                    "obtainable_qualifications",
    "オンボーディング制度・フォロー体制":                                    "onboarding_system",
    "女性活躍推進法に基づく一般事業主行動計画-内容":                            "female_promotion_plan",
    "女性活躍推進法に基づく一般事業主行動計画-リンクURL1":                       "female_promotion_plan_url1",
    "女性活躍推進法に基づく一般事業主行動計画-リンクURL2":                       "female_promotion_plan_url2",
    "女性活躍推進法に基づく一般事業主行動計画-リンクURL3":                       "female_promotion_plan_url3",
    "次世代育成支援対策推進法に基づく一般事業主行動計画-内容":                    "next_gen_support_plan",
    "次世代育成支援対策推進法に基づく一般事業主行動計画-リンクURL1":               "next_gen_support_plan_url1",
    "次世代育成支援対策推進法に基づく一般事業主行動計画-リンクURL2":               "next_gen_support_plan_url2",
    "次世代育成支援対策推進法に基づく一般事業主行動計画-リンクURL3":               "next_gen_support_plan_url3",
    "両立支援の取組事例-現在実施中又は実施していた取組・実績など＜育児休業関係＞":     "work_life_childcare_examples",
    "両立支援の取組事例-現在実施中又は実施していた取組・実績など＜仕事と介護の両立に関する取組＞":
        "work_life_caregiving_examples",
    "女性労働者に対する職業生活に関する機会の提供に資する社内制度の概要":           "female_career_opportunity_overview",
    "労働者の職業生活と家庭生活の両立に資する社内制度の概要":                    "work_life_balance_overview",
    "自由記述欄":                                                     "free_description",
    "自由ＰＲ欄":                                                     "free_pr",

    # ===== shokuba_certification (cols 500-636) =====
    "ハローワークインターネットサービスに掲載されている企業の求人情報-フルタイムの求人リンク":
        "hwis_fulltime_job_link",
    "ハローワークインターネットサービスに掲載されている企業の求人情報-パートタイムの求人リンク":
        "hwis_parttime_job_link",
    "ハローワークインターネットサービスに掲載されている企業の求人情報-大卒の求人リンク":
        "hwis_graduate_job_link",
    "ユースエール認定-認定有無":                                           "youth_excel_certified",
    "ユースエール認定-受賞年度":                                           "youth_excel_award_year",
    "その他の認定企業1":                                                 "other_certification1",
    "その他の認定企業1リンク":                                            "other_certification1_url",
    "その他の認定企業2":                                                 "other_certification2",
    "その他の認定企業2リンク":                                            "other_certification2_url",
    "その他の認定企業3":                                                 "other_certification3",
    "その他の認定企業3リンク":                                            "other_certification3_url",
    "えるぼし認定-認定有無":                                              "eruboshi_certified",
    "えるぼし認定-認定段階":                                              "eruboshi_level",
    "プラチナえるぼし認定-認定有無":                                        "platinum_eruboshi_certified",
    "トライくるみん-認定有無":                                            "try_kurumin_certified",
    "トライくるみん-認定状況":                                            "try_kurumin_status",
    "くるみん-認定有無":                                                 "kurumin_certified",
    "くるみん-認定状況":                                                 "kurumin_status",
    "プラチナくるみん-認定有無":                                           "platinum_kurumin_certified",
    "プラチナくるみん-認定年":                                            "platinum_kurumin_year",
    "トライくるみんプラス-認定有無":                                        "try_kurumin_plus_certified",
    "トライくるみんプラス-認定状況":                                        "try_kurumin_plus_status",
    "くるみんプラス-認定有無":                                            "kurumin_plus_certified",
    "くるみんプラス-認定状況":                                            "kurumin_plus_status",
    "プラチナくるみんプラス-認定有無":                                      "platinum_kurumin_plus_certified",
    "プラチナくるみんプラス-認定年":                                        "platinum_kurumin_plus_year",
    "安全衛生優良企業公表制度-認定有無":                                     "safety_health_certified",
    "安全衛生優良企業公表制度-認定期間":                                     "safety_health_period",
    "安全衛生優良企業公表制度-取組事例URL":                                  "safety_health_url",
    "なでしこ銘柄-認定有無":                                              "nadeshiko_certified",
    "なでしこ銘柄-選定年":                                               "nadeshiko_year",
    "ダイバーシティ経営企業1００選、または新・ダイバーシティ経営企業1００選-認定有無":  "diversity100_certified",
    "ダイバーシティ経営企業1００選、または新・ダイバーシティ経営企業1００選-表彰名":   "diversity100_award_name",
    "ダイバーシティ経営企業1００選、または新・ダイバーシティ経営企業1００選-受賞年度":  "diversity100_award_year",
    "100選プライム-表彰名":                                              "diversity100_prime_name",
    "100選プライム-受賞年度":                                            "diversity100_prime_year",
    "健康経営銘柄-認定有無":                                              "health_management_certified",
    "健康経営銘柄-選定年":                                               "health_management_year",
    "優良派遣事業者認定-認定有無":                                         "excellent_dispatch_certified",
    "優良派遣事業者認定-認定年度":                                         "excellent_dispatch_year",
    "優良派遣事業者認定-認定番号":                                         "excellent_dispatch_number",
    "優良派遣事業者認定-認定期限":                                         "excellent_dispatch_expiry",
    "製造請負優良適正事業者認定-認定有無":                                   "mfg_contract_certified",
    "製造請負優良適正事業者認定-認定年度":                                   "mfg_contract_year",
    "製造請負優良適正事業者認定-認定番号":                                   "mfg_contract_number",
    "製造請負優良適正事業者認定-認定期限":                                   "mfg_contract_expiry",
    "職業紹介事業者優良認定-認定有無":                                      "job_placement_certified",
    "職業紹介事業者優良認定-認定番号":                                      "job_placement_number",
    "職業紹介事業者優良認定-認定年度":                                      "job_placement_year",
    "職業紹介事業者優良認定-認定期限":                                      "job_placement_expiry",
    "グッドキャリア企業アワード-表彰有無":                                   "good_career_awarded",
    "グッドキャリア企業アワード-表彰名1":                                   "good_career_award_name1",
    "グッドキャリア企業アワード-受賞年度1":                                  "good_career_award_year1",
    "グッドキャリア企業アワード-表彰名2":                                   "good_career_award_name2",
    "グッドキャリア企業アワード-受賞年度2":                                  "good_career_award_year2",
    "グッドキャリア企業アワード-取組事例URL":                                "good_career_url",
    "無期転換制度-有無":                                                "indefinite_contract_exists",
    "無期転換制度-タイプ1":                                              "indefinite_contract_type1",
    "無期転換制度-タイプ2":                                              "indefinite_contract_type2",
    "無期転換制度-タイプ3":                                              "indefinite_contract_type3",
    "無期転換制度-概要":                                                "indefinite_contract_summary",
    "無期転換制度-詳細URL":                                             "indefinite_contract_url",
    "障害者雇用優良事業所の大臣表彰-表彰有無":                                "disability_emp_awarded",
    "障害者雇用優良事業所の大臣表彰-表彰名1":                               "disability_emp_award_name1",
    "障害者雇用優良事業所の大臣表彰-表彰年1":                               "disability_emp_award_year1",
    "障害者雇用優良事業所の大臣表彰-表彰名2":                               "disability_emp_award_name2",
    "障害者雇用優良事業所の大臣表彰-表彰年2":                               "disability_emp_award_year2",
    "高年齢者活躍企業コンテスト（旧称：高年齢者雇用開発コンテスト）-表彰有無":      "senior_worker_awarded",
    "高年齢者活躍企業コンテスト（旧称：高年齢者雇用開発コンテスト）-表彰名":       "senior_worker_award_name",
    "高年齢者活躍企業コンテスト（旧称：高年齢者雇用開発コンテスト）-表彰年度":      "senior_worker_award_year",
    "雇用管理改善関連-取組事例URL":                                        "employment_mgmt_url",
    "テレワーク推進企業等厚生労働大臣表彰-表彰有無":                            "telework_award_exists",
    "テレワーク推進企業等厚生労働大臣表彰-表彰名1":                            "telework_award_name1",
    "テレワーク推進企業等厚生労働大臣表彰-受賞年度1":                           "telework_award_year1",
    "テレワーク推進企業等厚生労働大臣表彰-表彰名2":                            "telework_award_name2",
    "テレワーク推進企業等厚生労働大臣表彰-受賞年度2":                           "telework_award_year2",
    "キャリア支援企業表彰-表彰有無":                                        "career_support_awarded",
    "キャリア支援企業表彰-受賞年度":                                        "career_support_award_year",
    "キャリア支援企業表彰-取組事例URL":                                     "career_support_url",
    "もにす（障害者雇用優良中小事業主認定表彰）-表彰有無":                       "monisu_awarded",
    "もにす（障害者雇用優良中小事業主認定表彰）-表彰名":                        "monisu_award_name",
    "登録日時":  "registered_at",
    "更新日時":  "updated_at",
}

# ---------------------------------------------------------------------------
# 日付カラム（正規化対象：英語カラム名）
# ---------------------------------------------------------------------------

DATE_COLUMNS: set[str] = {"registered_at", "updated_at"}

# ---------------------------------------------------------------------------
# テーブルごとのインデックス対象カラム
# ---------------------------------------------------------------------------

TABLE_INDEXES: dict[str, list[str]] = {
    "shokuba_basic":              ["corporate_number"],
    "shokuba_recruitment":        ["corporate_number"],
    "shokuba_work_hours":         ["corporate_number"],
    "shokuba_employment_system":  ["corporate_number"],
    "shokuba_female_workforce":   ["corporate_number"],
    "shokuba_childcare":          ["corporate_number"],
    "shokuba_career":             ["corporate_number"],
    "shokuba_certification":      ["corporate_number"],
}
