# -*- coding: utf-8 -*-
"""
ハローワーク求人データベース スキーマ定義・初期化
"""

import logging
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[5]))
from src.common.db_utils import open_connection

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# DDL
# ---------------------------------------------------------------------------

DDL_JOB_POSTINGS = """
CREATE TABLE IF NOT EXISTS job_postings (
    -- 求人基本情報
    job_number                    TEXT PRIMARY KEY,
    fetched_date                  TEXT NOT NULL,
    received_date                 TEXT,
    expiry_date                   TEXT,
    hello_work_office             TEXT,
    job_type_kbn                  TEXT,
    industry                      TEXT,
    online_application            TEXT,
    try_employed                  TEXT,
    -- 事業所情報
    establishment_number          TEXT,
    company_name_kana             TEXT,
    company_name                  TEXT,
    company_zip                   TEXT,
    company_address               TEXT,
    corporate_number              TEXT,
    representative_title          TEXT,
    representative_name           TEXT,
    established_year              TEXT,
    capital                       TEXT,
    employees_total               TEXT,
    employees_workplace           TEXT,
    employees_female              TEXT,
    employees_part                TEXT,
    labor_union                   TEXT,
    business_description          TEXT,
    company_feature               TEXT,
    company_notes                 TEXT,
    work_regulations_full         TEXT,
    work_regulations_part         TEXT,
    corporate_pension             TEXT,
    welfare_detail                TEXT,
    company_url                   TEXT,
    inquiry_contact1              TEXT,
    inquiry_contact2              TEXT,
    inquiry_contact3              TEXT,
    -- 仕事内容
    job_title                     TEXT,
    job_description               TEXT,
    employment_type               TEXT,
    employment_type_other         TEXT,
    contract_period               TEXT,
    contract_period_count         TEXT,
    contract_period_end           TEXT,
    contract_renewal              TEXT,
    contract_renewal_condition    TEXT,
    regular_conversion_record     TEXT,
    regular_conversion_count      TEXT,
    foreign_worker_record         TEXT,
    workplace_access              TEXT,
    workplace_access_note         TEXT,
    workplace_zip                 TEXT,
    workplace_address             TEXT,
    nearest_station               TEXT,
    commute_transport             TEXT,
    commute_time                  TEXT,
    smoking_policy                TEXT,
    smoking_policy_note           TEXT,
    transfer                      TEXT,
    transfer_area                 TEXT,
    uij_turn                      TEXT,
    mycar_commute                 TEXT,
    parking_available             TEXT,
    age_note                      TEXT,
    age_restriction               TEXT,
    age_restriction_range         TEXT,
    age_restriction_reason_type   TEXT,
    age_restriction_reason        TEXT,
    education                     TEXT,
    education_detail              TEXT,
    education_subject             TEXT,
    experience_required           TEXT,
    experience_detail             TEXT,
    pc_skills                     TEXT,
    license_necessity             TEXT,
    license_required              TEXT,
    license_other_necessity       TEXT,
    license_other_name            TEXT,
    license_other_input           TEXT,
    license_additional            TEXT,
    trial_period                  TEXT,
    trial_period_duration         TEXT,
    trial_period_condition        TEXT,
    trial_period_condition_detail TEXT,
    dispatch_flag                 TEXT,
    dispatch_number               TEXT,
    special_work_regulations      TEXT,
    hiring_reason                 TEXT,
    hiring_reason_other           TEXT,
    workplace_count               TEXT,
    workplace_1                   TEXT,
    workplace_2                   TEXT,
    workplace_3                   TEXT,
    workplace_current_location    TEXT,
    workplace_condition_note      TEXT,
    job_type_url                  TEXT,
    special_condition1            TEXT,
    special_condition2            TEXT,
    special_condition3            TEXT,
    recruitment_support           TEXT,
    job_change_form               TEXT,
    -- 賃金・手当
    wage                          TEXT,
    base_salary                   TEXT,
    wage_type                     TEXT,
    wage_type_other               TEXT,
    wage_type_note                TEXT,
    fixed_allowance               TEXT,
    fixed_allowance_rate          TEXT,
    fixed_overtime_flag           TEXT,
    fixed_overtime_amount         TEXT,
    fixed_overtime_detail         TEXT,
    other_allowances              TEXT,
    commute_allowance             TEXT,
    commute_allowance_unit        TEXT,
    commute_allowance_amount      TEXT,
    wage_closing_day              TEXT,
    wage_closing_day_other        TEXT,
    wage_closing_day_extra        TEXT,
    wage_payment_type             TEXT,
    wage_payment_month            TEXT,
    wage_payment_day              TEXT,
    wage_payment_extra            TEXT,
    pay_raise                     TEXT,
    pay_raise_record              TEXT,
    bonus                         TEXT,
    bonus_record                  TEXT,
    bonus_times                   TEXT,
    bonus_amount                  TEXT,
    annual_income1                TEXT,
    annual_income1_years          TEXT,
    annual_income2                TEXT,
    annual_income2_years          TEXT,
    annual_income3                TEXT,
    annual_income3_years          TEXT,
    -- 労働時間
    work_hours                    TEXT,
    work_hours_shift              TEXT,
    work_hours_2                  TEXT,
    work_hours_3                  TEXT,
    work_hours_or                 TEXT,
    work_hours_note               TEXT,
    flexible_work_unit            TEXT,
    weekly_work_days              TEXT,
    weekly_work_days_negotiable   TEXT,
    overtime_flag                 TEXT,
    overtime_hours_monthly        TEXT,
    avg_work_days_monthly         TEXT,
    article36_agreement           TEXT,
    break_time                    TEXT,
    break_room                    TEXT,
    weekly_holiday                TEXT,
    annual_holidays               TEXT,
    holiday_type                  TEXT,
    holiday_detail                TEXT,
    paid_leave_days               TEXT,
    -- その他の労働条件
    social_insurance              TEXT,
    social_insurance_extra        TEXT,
    retirement_fund_union         TEXT,
    retirement_fund_system        TEXT,
    retirement_fund_years         TEXT,
    retirement_age_system         TEXT,
    retirement_age                TEXT,
    rehire_system                 TEXT,
    rehire_age_limit              TEXT,
    work_extension_system         TEXT,
    work_extension_age_limit      TEXT,
    housing                       TEXT,
    housing_note                  TEXT,
    childcare_facility            TEXT,
    childcare_leave_record        TEXT,
    nursing_care_leave_record     TEXT,
    nursing_leave_record          TEXT,
    performance_pay_system        TEXT,
    performance_pay_detail        TEXT,
    rehire_other_system           TEXT,
    rehire_other_detail           TEXT,
    training_system               TEXT,
    training_for_non_regular      TEXT,
    barrier_free                  TEXT,
    elevator                      TEXT,
    handrail_stairs               TEXT,
    wheelchair_access             TEXT,
    display_facility              TEXT,
    handrail_installation         TEXT,
    -- 選考情報
    hiring_count                  TEXT,
    selection_method              TEXT,
    document_screening_result     TEXT,
    interview_result_timing       TEXT,
    result_notification_timing    TEXT,
    result_notification_method    TEXT,
    selection_schedule            TEXT,
    selection_schedule_note       TEXT,
    selection_venue_zip           TEXT,
    selection_venue_address       TEXT,
    selection_venue_station       TEXT,
    selection_venue_transport     TEXT,
    selection_venue_time          TEXT,
    selection_notes               TEXT,
    application_documents         TEXT,
    application_submission_method TEXT,
    application_doc_return        TEXT,
    other_doc_submission_method   TEXT,
    other_required_docs           TEXT,
    postal_submission_zip         TEXT,
    postal_submission_address     TEXT,
    contact_department            TEXT,
    contact_person                TEXT,
    contact_person_kana           TEXT,
    contact_phone                 TEXT,
    contact_fax                   TEXT,
    contact_extension             TEXT,
    contact_email                 TEXT,
    -- 特記事項
    special_notes                 TEXT,
    company_pr                    TEXT,
    -- 画像・座標
    pr_logo1                      TEXT,
    pr_logo2                      TEXT,
    pr_logo3                      TEXT,
    latitude1                     TEXT,
    longitude1                    TEXT,
    latitude2                     TEXT,
    longitude2                    TEXT,
    -- メタ情報
    source_file                   TEXT,
    loaded_at                     TEXT NOT NULL
);
"""

DDL_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_hw_corporate_number     ON job_postings (corporate_number);",
    "CREATE INDEX IF NOT EXISTS idx_hw_establishment_number ON job_postings (establishment_number);",
    "CREATE INDEX IF NOT EXISTS idx_hw_received_date        ON job_postings (received_date);",
    "CREATE INDEX IF NOT EXISTS idx_hw_expiry_date          ON job_postings (expiry_date);",
    "CREATE INDEX IF NOT EXISTS idx_hw_fetched_date         ON job_postings (fetched_date);",
]

# ---------------------------------------------------------------------------
# 初期化
# ---------------------------------------------------------------------------

def init_db(db_path: "str | Path") -> sqlite3.Connection:
    """DBファイルを作成し、テーブル・インデックスを初期化して接続を返す。"""
    conn = open_connection(db_path)
    conn.execute(DDL_JOB_POSTINGS)
    for idx_ddl in DDL_INDEXES:
        conn.execute(idx_ddl)
    conn.commit()
    logger.info("DB初期化完了: %s", db_path)
    return conn
